version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout  # checkout source code to working directory
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run: 
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - 'venv'
      - run:
          name: Running tests 
          command: |
              . venv/bin/activate
              python manage.py test
          environment:
              SECRET_KEY: '7shqww*5cd*5v*_m0d-o*t+iqe-x!cmub6x(ubn*o+)^(s4_ms'
      - store_artifacts:
          path: test_reports
          destination: tr1
      - store_test_results:
          path: test_reports

        
workflows:
  main:
    jobs:
      - build
